eureka:
  client:
    serviceUrl:
    #网上免费的eureka服务器
      defaultZone: http://eureka.didispace.com/eureka/
#      defaultZone: http://localhost:1001/eureka/
server:
  port: 9004
spring:
  application:
    name: pangdo-client
  cloud:
    sentinel:
      transport:
#        dashboard: 192.168.8.12:18085
        dashboard: 127.0.0.1:8080
      enabled: true
      eager: true