server:
  port: 8501

#Consul 的 注册中心
spring:
  application:
      name: spring-cloud-consul-producer
  cloud:
    consul:
      host: frp1.chuantou.org
      port: 54110
      discovery:
        healthCheckPath: /
        healthCheckInterval: 5s
        serviceName: service-producer