eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka.didispace.com/eureka/
server:
  port: 9102
spring:
  application:
    name: client-feign
feign:
  hystrix: 
    enabled: true
