server:
  #服务器端口
  port: 8080
  #服务器访问目录(不加，直接访问8080/即可)
  context-path: 

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/newb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  mvc:
    view:
      # 页面默认前缀目录  这里是支持JSP
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
      
#与通用mapper冲突 。不能加开发者pom
#  devtools:
#    restart:
#      #开发者工具，配置是否修改后自动重启
#      enabled: true

#mybatis:
#    type-aliases-package: com.newb.mybatis.db.entity
#    mapper-locations: classpath:mapper/*.xml


mapper:
    mappers:
        - com.newb.mybatis.db.service.common.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


application: 
  hello: Hello jsp From application