#server:
#服务器端口
#  port: 8081
#服务器访问目录(不加，直接访问8080/即可)，打为war包，必须为空
#  context-path: 

spring:
  #配置使用的配置 环境
  profiles:
     active: dev
#     active: prod
  
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/newb?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456

  mvc:
    view:
      # 页面默认前缀目录  这里是支持JSP
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
  aop:
    #使用cglib 动态代理，不然默认使用java动态代理，会导致无法扫描到service报错
    proxy-target-class: true
      
#与通用mapper冲突 。不能加开发者pom
#  devtools:
#    restart:
#      #开发者工具，配置是否修改后自动重启
#      enabled: true

#mybatis:
#    type-aliases-package: com.newb.mybatis.db.entity
#    mapper-locations: classpath:mapper/*.xml


mapper:
    mappers:
        - com.newb.mybatis.db.service.common.MyMapper
    not-empty: true
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    

application: 
  hello: Hello jsp From application