server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://119.23.231.239:3306/newb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 7262140
  # hibernate  
  jpa :
    database: MYSQL  
    hibernate:
      ddl-auto: update  
      dialect: org.hibernate.dialect.MySQL5Dialect  
    show-sql: true  
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect 
    
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid: 
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 1
      maxActive: 5
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      validationQuery: SELECT 1 
      testOnBorrow: true
      testWhileIdle: true
      testOnReturn: false
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat=true    
    
    
  primary: 
    name: testdb0
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.231.239:3306/newb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 7262140
    
  secondary: 
    name: testdb1
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.231.239:3306/newb2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 7262140

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
