server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/newb?useUnicode=true&characterEncoding=utf-8
    username: newb
    password: 123456